# String.JS
let str = "Benvenuto";
let str2 = 'va bene anche con le virgolette singole';
//backtick
let phrase = `si utilizza per funzionalità estese ${str}`;

//altre variabili

let name = "Carl";
alert( `Hello, ${name}!` ); //Hello, Carl!
alert( `il risultato è ${3+2}` ); //il risultato è 5

//valori booleani
let campoNomeSpuntato = true; //si il campo è spuntato
let campoCognomeSpuntato = false; //no il campo non è spuntato

//operazioni di confronto
let maggiore = 4 > 1;
alert( maggiore); // il risultato è si
